name: CI

on:
  pull_request:
  push:
    branches:
      - '**'
    tags-ignore:
      - v*.*.*

jobs:
  ci:

    name: Scala v${{ matrix.scala }} / Java v${{ matrix.java }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - java: 14
            scala: 2
          - java: 8
            scala: 3

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Setup Scala
        uses: japgolly/setup-everything-scala@v3.1
        with:
          java-version: adopt@1.${{ matrix.java }}

      - name: Build and test
        shell: bash
        run: |
          sbt++field scala${{ matrix.scala }} \
            -J-Xmx4G \
            -J-XX:+UseG1GC \
            test
